FROM python:3.12-slim

RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/dagster/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ /opt/dagster/app/src/

# gRPC server'ı başlat (Port 4000)
EXPOSE 4000

FROM python:3.12-slim

WORKDIR /opt/dagster/app
ENV DAGSTER_HOME=/opt/dagster/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY dagster.yaml workspace.yaml ./
COPY src/ /opt/dagster/app/src/

CMD ["python", "-m", "dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-m", "src.demo_pipeline.definitions"]
